### ISSUE TITLE
BPHunter_HIGHRISK and BPHUNTER_SCORE designations

### ISSUE THREAD

**Issue by emjblake** [casanova-lab/BPHunter#2]
How do you interpret BPHunter_HIGHRISK=NO with BPHUNTER_SCORE > 3? In this case, would a variant with this annotation potentially weaken the branchpoint, but not destroy it?

**Comment by zhangpeng1202** [comment]
Hi. Thanks for your message.
I added BPHunter_HIGHRISK for prioritizing the BP variants that are 1) disrupting the first/second BP of that intron, 2) the intron should have no more than 2 possible BP sites; 3) fitting the canonical BP motif; 4) supported by multiple data resources.
When you have BPHunter_HIGHRISK = NO but SCORE > 3, it is very likely suggesting this BP could be disrupted/weakened, but the splicing of the intron may not be significantly affected.
Thanks! Let me know.

**Comment by emjblake** [comment]
@zhangpeng1202, fantastic - thanks for the clarification!
